integration:
  open-e:
    external:
      username: username
      password: password
      url: http://oep-external.url
    internal:
      username: username
      password: password
      url: http://oep-internal.url
    external-soap:
      username: username
      password: password
      url: http://oep-external-soap.url
    internal-soap:
      username: username
      password: password
      url: http://oep-internal-soap.url
  support-management:
    url: http://support-management.url
  messaging:
    url: http://messaging.url
    channel: channel
    token: token
    mailRecipient: mailRecipient
  party:
    url: http://party.url
# OpenE Services

# Stats-only
stats-only:
  services:
    # Lämna synpunkt
    123:
      servicename: Lämna synpunkt
      priority: MEDIUM
      category: FEEDBACK_CATEGORY
      type: FEEDBACK_TYPE
      labels:
        - LABEL1
        - LABEL2
    456:
      servicename: Sundsvalls förslaget
      priority: MEDIUM
      category: PROPOSAL_CATEGORY
      type: PROPOSAL_TYPE

# OpenE Services - Other
ersattare-chef:
  family-id: 789
  priority: MEDIUM
  category: SYSTEM_MANAGEMENT
  type: SYSTEM_MANAGEMENT.SALARY_AND_WORKING_HOURS
ny-behorighet:
  family-id: 101
  priority: MEDIUM
  category: SYSTEM_MANAGEMENT
  type: SYSTEM_MANAGEMENT.PERMISSIONS
lonevaxling-pension:
  family-id: 111
  priority: MEDIUM
  category: PENSION
  type: PENSION.SALARY_EXCHANGE
kontakt-lon-pension:
  family-id: 121
  priority: MEDIUM
  category: SALARY
  type: SALARY.CONTACT_WANTED
tjugofem-ar-pa-jobbet:
  family-id: 131
  priority: MEDIUM
  category: SALARY
  type: SALARY.OTHER
  labels:
    - SALARY
    - SALARY.OTHER
    - SALARY.OTHER.TWENTY_FIVE_YEARS_GIFT
anmal-sjukfranvaro:
  family-id: 141
  priority: MEDIUM
  category: SALARY
  type: SALARY.ABSENCE
  labels:
    - SALARY
    - SALARY.ABSENCE
    - SALARY.ABSENCE.SICKNESS_ABSENCE
arbetsgivarintyg:
  family-id: 151
  priority: MEDIUM
  category: SALARY
  type: SALARY.AUTHORITY_LETTER
  labels:
    - SALARY
    - SALARY.AUTHORITY_LETTER
    - SALARY.AUTHORITY_LETTER.CERTIFICATE
foretradesratt-ateranstallning:
  family-id: 161
  priority: MEDIUM
  category: OTHER_COMPANIES
  type: OTHER_COMPANIES.PRECEDENCE
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          schema-generation:
            script:
              append: false
        column_ordering_strategy: legacy
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          support-management:
            token-uri: http://token.url
          party:
            token-uri: http://token.url
        registration:
          support-management:
            client-id: the-client-id
            client-secret: the-client-secret
          party:
            client-id: client-id
            client-secret: client-secret
  flyway:
    enabled: true
config:
  scheduler:
    fetch-days: 1
    keep-days: 14
    cron:
      caseprocessing: '0 0 */1 * * *'
      dbcleaner: '0 0 0 * * 7'
